### ISSUE TITLE
Cell By Category links to LS cell library not HD

### ISSUE THREAD

**Issue by dlmiles** [TinyTapeout/tt-support-tools#10]
https://github.com/TinyTapeout/tt-support-tools/blob/tt03/reports.py#L8

This links to LS not HD cells.

**Comment by mattvenn** [comment]
thanks for pointing that out. It looks like there is no public list of hd cells. Maybe we should have our own.

**Comment by dlmiles** [comment]
LS:

https://antmicro-skywater-pdk-docs.readthedocs.io/en/test-submodules-in-rtd/contents/libraries/sky130_fd_sc_ls/cells/

HD:

https://antmicro-skywater-pdk-docs.readthedocs.io/en/test-submodules-in-rtd/contents/libraries/sky130_fd_sc_hd/README.html
https://antmicro-skywater-pdk-docs.readthedocs.io/en/test-submodules-in-rtd/contents/libraries/sky130_fd_sc_hd/cells/inv/README.html

Not that the data appears any different :(   I am working on this what data sheets.

**Comment by dlmiles** [comment]
![image](https://user-images.githubusercontent.com/293087/235223230-05a3f3b4-1ddd-4b4e-ab1c-1baf6cdfd784.png)

Sample preview so far.  Working on liberty file data source ATM.  But I think I am still a few months away from first release, then it needs some kind of review (by someone who knows what they are doing).

**Comment by mattvenn** [comment]
very cool!
Let me know when you want a review!

**Comment by mattvenn** [comment]
see #12 - both are 404 now
