### ISSUE TITLE
check ports should happen after the source is fetched

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-support-tools#20]
https://github.com/TinyTapeout/tt-support-tools/blob/887e208b86f6ef62d9afd626669e42c4649ff5f8/tt_tool.py#L65
otherwise the port check fails as there is no source

**Comment by urish** [comment]
This is only relevant for Wokwi projects, right?

I think we can simply waive this check for Wokwi projects. Otherwise, we can probably move it into create_user_config(), right after fetching the Wokwi sources.

, WDYT?

**Comment by mattvenn** [comment]
yes this error only occurs with wokwi projects. either solution works for me
