### ISSUE TITLE
this fails with projects that manually instantiate standard cells

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-support-tools#31]
https://github.com/TinyTapeout/tt-support-tools/blob/e8c5040dc5098d3b90f07b3f0c41d2e211ff575d/project.py#L803

example failure:

https://github.com/MisguidedBadge/Tzeentch_tt/actions/runs/7975527928/job/21773962803#step:3:1416

**Comment by urish** [comment]
You wrote this assertion - do you remember what was the intention? Is there any good reason to keep it?

**Comment by mattvenn** [comment]
No I don't remember the intention, I think we can get rid of it
