### ISSUE TITLE
add a note about setting up new repo GH_TOKEN

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-support-tools#5]
actions won't work without it

**Comment by mattvenn** [comment]
repo - > settings -> secrets & variables -> actions -> new repo secret

one for GH_USERNAME
one for GH_TOKEN

**Comment by urish** [comment]
Still relevant? 

See tinytapeout/tinytapeout-03p5#17

**Comment by mattvenn** [comment]
I don't know, haven't followed that PR

**Comment by urish** [comment]
Irrelevant - tinytapeout-04 works without `GH_TOKEN` / `GH_USERNAME`
