### ISSUE TITLE
tt07 is broken on python 3.12

### ISSUE THREAD

**Issue by Ravenslofty** [TinyTapeout/tt-support-tools#53]
The `tt07` branch has a `requirements.txt` that specifies several package versions which do not support python 3.12.

https://github.com/TinyTapeout/tt-support-tools/blob/29e3bc4c3fea7c5308f9ec6b2ad20b7734386050/requirements.txt#L17 numpy 1.26 is needed for Python 3.12 support.

https://github.com/TinyTapeout/tt-support-tools/blob/29e3bc4c3fea7c5308f9ec6b2ad20b7734386050/requirements.txt#L22 PyYAML 6.0.1 is needed for Python 3.12 support.

These changes are enough to get this to install, however I realise that a goal is to get reproducible builds, which is why I'm leaving this as an issue for people to decide on.

**Comment by urish** [comment]
Thanks!
