### ISSUE TITLE
docs should fail if image is specced but not found

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-support-tools#7]

**Comment by grant-h** [comment]
Additionally when building a PDF fails, it should likely `exit(1)` to fail the GitHub docs action. Currently the failure is log only
![image](https://user-images.githubusercontent.com/3030665/230662302-98b1fda6-92c1-4eea-a42a-aefba3cbc436.png)

**Comment by mattvenn** [comment]
fixed with #c99cfc1
